version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: customer_app_db
    ports:
      - "5432:5432"
    networks:
      - common-network
#  app:
#    image: coffee-shop-chain
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    environment:
#      DATABASE_URL: jdbc:postgresql://db:5432/customer_app_db
#      DATABASE_USER: admin
#      DATABASE_PASSWORD: admin
#    networks:
#      - common-network

networks:
  common-network:
    driver: bridge